name: Create release branches
on:
  push:
    branches:
      - master
#  pull_request:
#    types: [closed]
#    branches:
#      - main

jobs:
  create-release-preproduction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#        with:
#          ref: preproduction

      - name: Cherry-pick last commit
        run: |
          set -x
          git config --global user.email "mu-bot@toasttab.com"
          git config --global user.name "Ministry of User Bot"
          
          sha=$(git log -n 1 --pretty=format:"%H")
          branch_name="${sha}-preproduction"
          git fetch
          git checkout preproduction
          git log
          
          git checkout -b ${branch_name}
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
#          git cherry-pick master
#          git push origin ${branch_name}
#          echo "done"
#      - name: Create PR

