name: Create release branches
on:
  push:
    branches:
      - test-preproduction
#  pull_request:
#    types: [closed]
#    branches:
#      - main

jobs:
  create-release-preproduction:
    runs-on: ubuntu-latest
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v2
        with:
          ref: preproduction
#      - name: Create new branch
#        uses: peterjgrainger/action-create-branch@v2.0.1
#        with:
#          branch: ${{ GITHUB_REF }}-preproduction
      - name: Print environment
        run: env
      - name: Cherry-pick last commit
        run: |
          set -x
          branch_name=$GITHUB_REF
          echo "${branch_name}"
          git checkout -b ${branch_name-preproduction}; 
          git cherry-pick main
          git push --set-upstream origin ${branch_name-preproduction}

