name: Create release branches
on:
  push:
    branches:
      - master
#  pull_request:
#    types: [closed]
#    branches:
#      - main

jobs:
  create-release-preproduction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry-pick last commit
        run: .github/workflows/scripts/perform-cherrypick.sh preproduction
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: preproduction
          title: ${{ env.commit_title }} (preproduction)
          labels: preproduction
          branch: ${{ env.branch_name }}
          body: This PR was created automatically to preproduction from the commit https://github.com/antonlisovenko/sandbox/commit/${{ env.commit_sha }}


#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1
#




