name: Create release branches
on:
  push:
    branches:
      - test-preproduction
#  pull_request:
#    types: [closed]
#    branches:
#      - main

jobs:
  create-release-preproduction:
    runs-on: ubuntu-latest
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v2
        with:
          ref: preproduction
      - name: Print environment
        run: env
      - name: Cherry-pick last commit
        run: |
          set -x          
          git config --global user.email "mu-bot@toasttab.com"
          git config --global user.name "Ministry of User Bot"
          sha=$(git log -n 1 --pretty=format:"%H")
          branch_name="${sha}-preproduction"
          git checkout -b ${branch_name}
          git cherry-pick ${sha}
          git push origin ${branch_name}
#      - name: Create PR

