name: Create release branches
on:
  push:
    branches:
      - master
#  pull_request:
#    types: [closed]
#    branches:
#      - main

jobs:
  create-release-preproduction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

